import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const links = [
  { name: "Latest", id: "/latest" },
  { name: "Entertainment", id: "/entertainment" },
  { name: "World", id: "/world" },
  { name: "Business", id: "/business" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul className="flex flex-row justify-evenly">
            {links.map((link) => (
              <li key={link.name}>
                <Link href={link.id}>{link.name}</Link>
              </li>
            ))}
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
